#!/bin/bash
# Wrapper around PHP CodeSniffer invocation script
# https://github.com/s0enke/git-hooks.git

# Allows the user to decide if he wants to proceed with
# the commit or not in case of errors

ORIGINAL_DIR=`pwd`

cd "$(git rev-parse --show-toplevel)"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/git-hooks/phpcs-pre-commit/pre-commit
RETVAL=$?
 
if [ $RETVAL -ne 0 ]; then
  echo "$OUTPUT" | less
  echo "Do you wish to commit?"
  select yn in "Yes" "No"; do
    case $yn in
      Yes )
        exit 0
        ;;
      No )
        break
        ;;
     esac
  done
fi

cd "$ORIGINAL_DIR"
exit $RETVAL
